<<<<<<< HEAD
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
=======
key: val
>>>>>>> 35560cc2a00444b1a2bc5fb6679de6605b2c7b93
